name: Fly Deploy Staging
on:
  pull_request:
    branches: [main]

jobs:
  deploy:
    name: Deploy Staging
    environment: staging
    runs-on: ubuntu-latest
    concurrency: deploy-staging-group # Single concurrency
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --config ./fly.staging.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_STAGING }}