name: Fly Deploy Staging
on:
  pull_request:
    branches: [main]

jobs:
  deploy:
    name: Deploy Staging
    environment:
      name: staging
      url: https://danielwilton-portfolio-dev.fly.dev/
    runs-on: ubuntu-latest
    concurrency: deploy-staging-group # Single concurrency
    steps:
      - uses: actions/checkout@v4

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy 🚀
        run: |
          flyctl deploy --remote-only --config ./fly.staging.toml
          echo "new_page_url=${{ steps.deployment.outputs.page_url }}notebook/" >> $GITHUB_OUTPUT
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_STAGING }}
