name: Deploy to GitHub Pages PR Preview

on:
  push:
    branches: [main]

concurrency: main-gh-pages

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1

      - name: Install and Build
        run: |
          bun install
          URL_PREFIX="portfolio" bun run build

      - uses: actions/upload-artifact@master
        with:
          name: github-pages
          path: ./dist/
      
      
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - uses: actions/download-artifact@master
        with:
          name: github-pages
          path: ./dist/

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # The folder the action should deploy.